server:
  port: 9701

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinlin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: pinlin
    password: javaq159

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
